// worker.js
importScripts('magic_compiler.js'); // Generated by Emscripten

self.onmessage = function(e) {
    const { input } = e.data;

    try {
        const result = Module.compileMagic(input);
        self.postMessage({ success: true, data: JSON.parse(result) });
    } catch (error) {
        self.postMessage({ success: false, error: error.message });
    }
};